window.MAISTER_DATA = {
  generated: "2026-09-27T17:35:11Z",
  task: {
    title: "Migracja motywu na Material 3 + dark mode",
    type: "development",
    status: "in_progress",
    description: "Theme.BlackBox: MaterialComponents -> Material 3, color scheme, typography/shape tokens, values-night, remove forceDarkAllowed=false.",
    path: ".maister/tasks/development/2026-09-27-material3-dark-mode",
    current_activity: "Implementation committed; verification (Phase 10/11) not yet run"
  },
  characteristics: {has_reproducible_defect: false, modifies_existing_code: true, creates_new_entities: false, involves_data_operations: true, ui_heavy: true},
  phases: [
    { id: "phase-1", name: "Codebase analysis & clarifications", icon_hint: "analysis", status: "completed", started: "2026-09-27T07:31:13Z", completed: "2026-09-27T07:50:44Z", skip_reason: null,
      summary: "Theme swap to Material3.DayNight is small (MDC 1.12.0 ships it); real work is ~20 hard-coded light colors and third-party widgets reading colorPrimary. Guest apps unaffected; no tests.",
      decisions: [{decision: "Toolbar: M3 surface style", rationale: "Standard M3, readable in both modes"}, {decision: "Custom M3 palette + dynamic color on Android 12+", rationale: "User choice"}, {decision: "Theme-mode ListPreference System/Light/Dark, default System", rationale: "User choice; no restart"}, {decision: "Bcore LauncherActivity flash out of scope", rationale: "Separate task"}],
      risks: ["Night mode must be gated to main process (App.onCreate runs in every :pN stub process)", "MainActivity.kt:253 toolbar.getChildAt(1) fragile", "No tests - manual light/dark verification", "Seed color not chosen yet"],
      artifacts: [{path: "analysis/codebase-analysis.md", label: "Codebase analysis", html: null}, {path: "analysis/clarifications.md", label: "Clarifications", html: null}], gate: null },
    { id: "phase-2", name: "Gap analysis & scope", icon_hint: "analysis", status: "completed", started: "2026-09-27T07:50:44Z", completed: "2026-09-27T08:00:19Z", skip_reason: null,
      summary: "Medium risk, modificative UI change. DynamicColors/night-mode init must be gated to main process + host activities; theme-mode pref needs a single source of truth.",
      decisions: [{decision: "Seed color blue ~#3F6FD8 + neutral surfaces", rationale: "Chromatic primary needed"}, {decision: "material-dialogs styled via md_* attrs", rationale: "Focused diff"}, {decision: "Tokens: theme-level + touched layouts", rationale: "No unrelated refactor"}, {decision: "Remove only obsolete theme/color entries; keep dead layouts", rationale: "User choice"}, {decision: "osmdroid tiles stay light", rationale: "Inverted tiles look odd"}, {decision: "Toolbar subtitle click re-implemented robustly", rationale: "User choice"}, {decision: "Dynamic color always on API 31+, no toggle", rationale: "Not requested"}],
      risks: ["DynamicColors would restyle guest :pN activities and Bcore LauncherActivity unless gated", "Settings stored twice (default prefs + loader) can drift", "Fixed color resources (CornerLabelView, CatLoadingView, AppsAdapter) won't follow Material You"],
      artifacts: [{path: "analysis/gap-analysis.md", label: "Gap analysis", html: null}, {path: "analysis/scope-clarifications.md", label: "Scope clarifications", html: null}], gate: {question: "Continue to Phase 4: UI mockups?", answer: "Yes, generate mockups"} },
    { id: "phase-3", name: "TDD red gate", icon_hint: "verify", status: "skipped", started: null, completed: null, skip_reason: "No reproducible defect", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-4", name: "UI mockups", icon_hint: "spec", status: "completed", started: "2026-09-27T08:00:19Z", completed: "2026-09-27T08:09:22Z", skip_reason: null, summary: "11 HTML mockups (light+dark) of the M3 re-theme, seed #3F6FD8. Live gallery: http://localhost:3847", decisions: [], risks: ["Palette values in mockups are approximations; final tonal palette generated in implementation"], artifacts: [{path: "analysis/design-context/INDEX.md", label: "Design context index", html: null}, {path: "analysis/design-context/mockups/main-apps-grid.html", label: "Mockup: main grid", html: "analysis/design-context/mockups/main-apps-grid.html"}, {path: "analysis/design-context/mockups/settings-with-theme-preference.html", label: "Mockup: settings", html: "analysis/design-context/mockups/settings-with-theme-preference.html"}], gate: {question: "Accept mockups and continue to Phase 5?", answer: "Accepted"} },
    { id: "phase-5", name: "Requirements & specification", icon_hint: "spec", status: "completed", started: "2026-09-27T08:09:22Z", completed: "2026-09-27T08:27:36Z", skip_reason: null, summary: "Material3.DayNight, 34-role scheme from #3F6FD8, DynamicColors API31+ gated, surface toolbar, tokens, Appearance>Theme preference. 20 requirements, 16-row manual QA.", decisions: [{decision: "DynamicColors precondition: class name starts with top.niunaijun.blackboxa. (trailing dot)", rationale: "Excludes Bcore LauncherActivity"}, {decision: "@color/primary kept only for CatLoadingView", rationale: "White label contrast"}, {decision: "Status bar surface + dark icons via values-v23", rationale: "API 21-22 limitation"}, {decision: "WelcomeTheme extends Theme.BlackBox", rationale: "No white flash"}], risks: ["Third-party XML attrs may not accept ?attr/ - fallback night-aware @color tokens", "ListPreference dialog 28dp corners only on API 28+", "No automated safety net"], artifacts: [{path: "implementation/spec.md", label: "Specification", html: "implementation/spec.html"}, {path: "analysis/requirements.md", label: "Requirements", html: null}], gate: {question: "Continue to specification audit?", answer: "Yes"} },
    { id: "phase-6", name: "Specification audit", icon_hint: "verify", status: "skipped", started: null, completed: null, skip_reason: "Skipped by user", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-7", name: "Implementation planning", icon_hint: "plan", status: "completed", started: "2026-09-27T08:32:23Z", completed: "2026-09-27T08:41:14Z", skip_reason: null, summary: "6 task groups, 46 steps, linear chain 1-6; 11/11 mockups covered; verification = assembleDebug per group + manual QA.", decisions: [{decision: "ThemeOverlay.BlackBox.Toolbar defined in Group 3 next to its only consumer", rationale: "Staged removals keep each build green"}, {decision: "Third-party widget attrs pre-checked; fallback to @color/md_theme_* pre-authorized", rationale: "Library sources unavailable"}], risks: ["resolved: toolchain installed (JDK 21 + SDK/NDK on D:), baseline build green", "Group 6 manual QA must be run by user on device/emulator", "Toolbar subtitle TextView looked up once after subtitle set"], artifacts: [{path: "implementation/implementation-plan.md", label: "Implementation plan", html: "implementation/implementation-plan.html"}, {path: "implementation/visual-coverage.md", label: "Visual coverage", html: null}], gate: {question: "Continue to implementation? Build verification?", answer: "Yes; user installs Android SDK + JDK 21 first"} },
    { id: "phase-8", name: "Implementation", icon_hint: "code", status: "completed", started: "2026-09-27T09:09:41Z", completed: "2026-09-27T17:35:11Z", skip_reason: null, summary: "Groups 1-5 + build/checklist done; full assembleDebug green; 26 app files changed; Bcore untouched. Manual QA pending on user device.", decisions: [{decision: "Primary palette chroma 48 (day #395BA9, night #B1C5FF)", rationale: "User chose livelier blue"}, {decision: "Third-party widget colors via ?attr/", rationale: "Libraries read attrs via obtainStyledAttributes"}], risks: ["resolved: manual QA confirmed by user on RMX3363 (API 33)", "SimpleSearchView cursor color may not apply on newer Android", "GMS rows lack mockup summary line"], artifacts: [{path: "implementation/work-log.md", label: "Work log", html: null}, {path: "verification/manual-qa-checklist.md", label: "Manual QA checklist", html: null}, {path: "implementation/implementation-plan.md", label: "Plan progress", html: "implementation/implementation-plan.html"}], gate: {question: "Continue to verification?", answer: "QA done by user; commit theme, merge fix"} },
    { id: "phase-9", name: "TDD green gate", icon_hint: "verify", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-10", name: "Verification options", icon_hint: "verify", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-11", name: "Verification & fixes", icon_hint: "verify", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-12", name: "E2E testing", icon_hint: "verify", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-13", name: "User documentation", icon_hint: "docs", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-14", name: "Finalization", icon_hint: "done", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null }
  ],
  verification: { status: null, issues: [], fixes: [], reverify_count: 0 }
};
