package top.niunaijun.blackboxa.util

import java.io.File

/** Copies an app data directory for a duplicated user. */
object DataDirCopier {

    /** Top-level directories that are regenerated by the app or the engine and never copied or backed up. */
    val SKIPPED_DIRS = setOf("lib", "cache", "code_cache")

    /** True when [file] is a symbolic link, which would point back at the user it was copied from. */
    fun isSymbolicLink(file: File): Boolean {
        val parent = file.absoluteFile.parentFile ?: return false
        return file.canonicalFile != File(parent.canonicalFile, file.name)
    }

    /**
     * Copies everything in [source] into [target] except the directories that get regenerated
     * (native libs and caches) and symbolic links, which would point back at the source user.
     */
    fun copy(source: File, target: File) {
        val entries = source.listFiles() ?: return
        target.mkdirs()
        entries.filter { it.name !in SKIPPED_DIRS && !isSymbolicLink(it) }
                .forEach { it.copyRecursively(File(target, it.name), overwrite = true) }
    }
}
